### ISSUE TITLE
How to pass computing numeric result from one task to the next task?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [dexecutor/dexecutor-examples#1]
Hi,
    I have read you codes and run the "WorkFlowApplication" from localhost, the execution result is the same as you have written in README.md file. Now, the result of one task is a boolean value. However, I am so confused about when I execute the "Task 3" which need a numerical param variable as the "Task 2" computing result, such as "int j =2;", that is the computing integer result from "Task 2". So, could you pls help to give me some suggestions on how to pass computing numeric result from one task to the next task? Thanks!

Note: I need the following procedure: When "Task 1" has been executed, the "i = 1" has been got. When "Task 2" has been executed, the "j = 2" has been got. Then, "Task 3" will be reached if the result of "Task 2" is True. But now, "Task 3" need the "i = 1, j = 2" from "Task 1" and "Task 2", so could you pls help to tell me how to get "i, j" variables from previous tasks?

**Comment by mnadeem** [comment]
This requires a change in API,

I will change the API to get any Task result value from any other Task, this way, if you are curretnly executing Task C and need the values for Task A and Task B, you can get by ids of taks A and task B

**Comment by JenniferYingyiWu2020** [comment]
OK, I got it. Thanks!

**Comment by mnadeem** [comment]
https://github.com/dexecutor/dexecutor-core/commit/fb23e3383fa87ce010aef6f53fbfb940c517e0d8 Code has been checked in

**Comment by mnadeem** [comment]
```
<dependency>
  <groupId>com.github.dexecutor</groupId>
  <artifactId>dexecutor-core</artifactId>
  <version>2.1.2</version>
</dependency>
```
